---
name: move a major tag to the latest release

on:
  push:
    tags:
       - v**

permissions:
  contents: write

jobs:
  tag:
    name: move major tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      #- uses: phwt/major-tagging-action@v1
      # c&p :(
      - name: setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "action@github.com"

      - name: re-tagging major tag
        run: |
          CURRENT_TAG=$(git describe --tags)
          MAJOR_TAG=$(awk -F'.' '{print $1}' <<<"$CURRENT_TAG")

          # Remove remote old major tag if exists
          REMOTE_RESULT=$(git ls-remote --tags origin -l "$MAJOR_TAG")
          if [[ $REMOTE_RESULT ]]; then
            echo "Moving major tag '$MAJOR_TAG' to the same commit as '$CURRENT_TAG' tag"
            git push --delete origin $MAJOR_TAG
          else
            git push --delete origin $MAJOR_TAG
          fi
          git tag $MAJOR_TAG
          git push origin $MAJOR_TAG

