---
name: move a major tag to the latest release

on:
  push:
    tags:
       - v**

permissions:
  contents: write

jobs:
  tag:
    name: move major tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: phwt/major-tagging-action@v1
