---
name: merge dependabot

on:
  workflow_call:

jobs:
  merge:
    name: 'merge dependabot'
    runs-on: ubuntu-latest
    steps:
    - if: ${{ github.event.workflow_run.conclusion == 'success' }}
      name: merge
      uses: ridedott/merge-me-action@v2
      with:
        GITHUB_TOKEN: ${{ secrets.unprotect_the_protected }}
        MERGE_METHOD: MERGE
        PRESET: DEPENDABOT_MINOR
        ENABLE_GITHUB_API_PREVIEW: true

