---
name: publish
on:
  workflow_call:
    inputs:
      tag_name:
        type: string
        required: true
      javaVersion:
        type: number
        default: 17

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.tag_name }}

      - name: import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          passphrase: ${{ secrets.gpg_passphrase }}

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.javaVersion }}
          distribution: zulu

      - name: cache maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: setup maven settings.xml
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: >
            [
              {
                "id": "ossrh",
                "username": "${{ secrets.mvn_username }}",
                "password": "${{ secrets.mvn_password }}"
              }
            ]

      - name: build and publish
        run: |
          mvn --batch-mode --no-transfer-progress -Possrh deploy
